export const universities = [
  { value: "mit", label: "Massachusetts Institute of Technology" },
  { value: "harvard", label: "Harvard University" },
  { value: "stanford", label: "Stanford University" },
  { value: "caltech", label: "California Institute of Technology" },
  { value: "princeton", label: "Princeton University" },
  { value: "yale", label: "Yale University" },
  { value: "columbia", label: "Columbia University" },
  { value: "uchicago", label: "University of Chicago" },
  { value: "upenn", label: "University of Pennsylvania" },
  { value: "cornell", label: "Cornell University" },
  { value: "duke", label: "Duke University" },
  { value: "northwestern", label: "Northwestern University" },
  { value: "jhu", label: "Johns Hopkins University" },
  { value: "dartmouth", label: "Dartmouth College" },
  { value: "brown", label: "Brown University" },
  { value: "vanderbilt", label: "Vanderbilt University" },
  { value: "rice", label: "Rice University" },
  { value: "notredame", label: "University of Notre Dame" },
  { value: "berkeley", label: "University of California, Berkeley" },
  { value: "ucla", label: "University of California, Los Angeles" },
  { value: "usc", label: "University of Southern California" },
  { value: "georgetown", label: "Georgetown University" },
  { value: "umich", label: "University of Michigan" },
  { value: "unc", label: "University of North Carolina at Chapel Hill" },
  { value: "uva", label: "University of Virginia" },
  { value: "wustl", label: "Washington University in St. Louis" },
  { value: "nyu", label: "New York University" },
  { value: "tufts", label: "Tufts University" },
  { value: "ucsd", label: "University of California, San Diego" },
  { value: "ucdavis", label: "University of California, Davis" },
  { value: "bu", label: "Boston University" },
  { value: "northeastern", label: "Northeastern University" },
  { value: "uiuc", label: "University of Illinois Urbana-Champaign" },
  { value: "uw", label: "University of Washington" },
  { value: "gatech", label: "Georgia Institute of Technology" },
  { value: "utaustin", label: "University of Texas at Austin" },
  { value: "wisc", label: "University of Wisconsin-Madison" },
  { value: "purdue", label: "Purdue University" },
  { value: "osu", label: "Ohio State University" },
  { value: "psu", label: "Pennsylvania State University" },
  { value: "other", label: "Other" },
]

export const majors = [
  { value: "computer_science", label: "Computer Science" },
  { value: "engineering", label: "Engineering" },
  { value: "business", label: "Business" },
  { value: "medicine", label: "Medicine" },
  { value: "law", label: "Law" },
  { value: "arts", label: "Arts" },
  { value: "humanities", label: "Humanities" },
  { value: "social_sciences", label: "Social Sciences" },
  { value: "natural_sciences", label: "Natural Sciences" },
  { value: "mathematics", label: "Mathematics" },
  { value: "education", label: "Education" },
  { value: "other", label: "Other" },
]

export const industries = [
  { value: "technology", label: "Technology" },
  { value: "healthcare", label: "Healthcare" },
  { value: "finance", label: "Finance" },
  { value: "education", label: "Education" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "retail", label: "Retail" },
  { value: "media", label: "Media & Entertainment" },
  { value: "consulting", label: "Consulting" },
  { value: "real_estate", label: "Real Estate" },
  { value: "energy", label: "Energy" },
  { value: "transportation", label: "Transportation" },
  { value: "hospitality", label: "Hospitality" },
  { value: "agriculture", label: "Agriculture" },
  { value: "government", label: "Government" },
  { value: "nonprofit", label: "Non-profit" },
  { value: "other", label: "Other" },
]

export const companySizes = [
  { value: "startup", label: "Startup (1-10 employees)" },
  { value: "small", label: "Small (11-50 employees)" },
  { value: "medium", label: "Medium (51-200 employees)" },
  { value: "large", label: "Large (201-1000 employees)" },
  { value: "enterprise", label: "Enterprise (1000+ employees)" },
]
