"use server"

import { createClient } from "@/lib/supabase/server"
import { revalidatePath } from "next/cache"
import { cookies } from "next/headers"

interface CreatePostArgs {
  title: string
  content: string
  authorId: string
  // Add any other fields relevant to your 'posts' table, e.g., user_type
}

export async function createPost(data: CreatePostArgs) {
  const cookieStore = cookies()
  const supabase = createClient(cookieStore)

  const { title, content, authorId } = data

  if (!authorId) {
    return { error: "User not authenticated." }
  }

  if (!title || !content) {
    return { error: "Title and content are required." }
  }

  try {
    const { data: postData, error } = await supabase
      .from("posts")
      .insert([
        {
          user_id: authorId, // Ensure this matches your 'posts' table column name for author ID
          title: title, // Ensure this matches your 'posts' table column name for title
          content: content, // Ensure this matches your 'posts' table column name for content
          // Add other fields like 'created_at' if not auto-generated by DB
        },
      ])
      .select()
      .single() // Assuming you want to get the created post back

    if (error) {
      console.error("Supabase error creating post:", error.message)
      return { error: `Database error: ${error.message}` }
    }

    // Revalidate the path where posts are displayed, e.g., the main feed or user's profile
    // Adjust the path as necessary
    revalidatePath("/")
    // If posts are also on profile pages, you might revalidate those too, e.g., revalidatePath(`/profile/${authorId}`)
    // Or use revalidateTag if you're using tags for caching.

    return { data: postData, error: null }
  } catch (e: any) {
    console.error("Unexpected error creating post:", e.message)
    return { error: `An unexpected error occurred: ${e.message}` }
  }
}

// You can add other server actions here as your application grows.
